### ISSUE TITLE
@Theoyeah, we have a problem

### ISSUE THREAD

**Issue by Wither362** [Theoyeah/Theoyeah-Engine#104]
https://github.com/Theoyeah/Theoyeah-Engine/blob/fa29ffefad271cd1307cde5d76bb2a4068ac6565/.github/workflows/main.yml#L142

Is not the `/export/32bit/windows/bin`, is the `/export/release/windows/bin`, the same as the x64 compile folder, now we have a big problem

**Comment by Wither362** [comment]
Fuck, @Theoyeah, with the new commit you do we have this other problem 
![fucking github](https://user-images.githubusercontent.com/93864752/168740786-039caf4b-5ddc-45e6-bd53-343245bacc19.png)

**Comment by Theoyeah** [comment]
Fixed in a commit
