### ISSUE TITLE
Again

### ISSUE THREAD

**Issue by Wither362** [Theoyeah/Theoyeah-Engine#107]
### Describe your bug here.

Again @Theoyeah, 
![A2F2EF91-DB7B-4922-AEFC-36030AF505B4](https://user-images.githubusercontent.com/93864752/168768606-a03d8bd0-b48a-4ada-85c0-4b3d542463e3.png)
The freaking windows 32 thing

### Are you modding a build from source or with Lua?

F*ck is from the engine

### What is your build target?

FROM THE ENGINE!!!!

### Did you edit anything in this build? If so, mention or summarize your changes.

FROM THE ENGINE

**Comment by Theoyeah** [comment]
Ok that's getting weird, everything is correct but idk why but github can't find it

**Comment by Wither362** [comment]
If you compile the 32 version, you can see that is the same folder that the windows one

**Comment by Wither362** [comment]
But I don’t know how to change the compile folder

**Comment by Theoyeah** [comment]
![image](https://user-images.githubusercontent.com/97792861/168770742-dec0d1c9-9da1-4c71-bce6-12ab5f5adf18.png)
It is totally the correct folder

**Comment by Wither362** [comment]
Look at the compile thing ENTIRE, look it ENTIRE, from up to down, and you’ll find some interesting things

**Comment by Wither362** [comment]
Also, the #103 more combo equals more score is finished, and works perfectly, do you want it in the engine?

**Comment by Theoyeah** [comment]
> Also, the #103 more combo equals more score is finished, and works perfectly, do you want it in the engine?

I'll see thta later, i'll check the compile logs like you said

**Comment by Wither362** [comment]
Ok

**Comment by Theoyeah** [comment]
Idk why but when compiling the thing targets the windows folder, but not the 32x folder

**Comment by Wither362** [comment]
Yeah! Exactly! Now look at the project xml

**Comment by Wither362** [comment]
And you’ll see other interesting thing

**Comment by Theoyeah** [comment]
Oh wait.... i put -32 instead of -32bits. I think that it was the problem
![image](https://user-images.githubusercontent.com/97792861/168776118-150b5f4a-abc3-414b-b978-5bae7fcd5664.png)
