### ISSUE TITLE
AH FUCK IT

### ISSUE THREAD

**Issue by Theoyeah** [Theoyeah/Theoyeah-Engine#180]
### Describe your bug here.

![image](https://user-images.githubusercontent.com/97792861/173083596-824bd9a6-1bd7-469c-829c-00ba032ec506.png)
![image](https://user-images.githubusercontent.com/97792861/173084105-10331525-85fb-4acf-ad5d-3579b48b570d.png)

Im trying to fix this error when compiling html5 (yes im fixing it myself)
Do you know any way to fix it ?

### Are you modding a build from source or with Lua?

F*ck is from the engine

### What is your build target?

HTML5

### Did you edit anything in this build? If so, mention or summarize your changes.

jhdjk

**Comment by Wither362** [comment]
Okokokokok

**Comment by Wither362** [comment]
I will repair it

**Comment by Wither362** [comment]
Fixed

**Comment by Theoyeah** [comment]
ok gonna try
