### ISSUE TITLE
Oh god, the game is broken

### ISSUE THREAD

**Issue by Theoyeah** [Theoyeah/Theoyeah-Engine#201]
### Describe your bug here.

When i play any song, the game just crashes ):

### Are you modding a build from source or with Lua?

F*ck is from the engine

### What is your build target?

FROM THE ENGINE!!!!

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by Wither362** [comment]
i cant see where is the error, i need help with it

**Comment by Wither362** [comment]
or... maybe is from the actual psych engine... because i have been hearing some things about errors...

**Comment by Wither362** [comment]
# @Theoyeah!! I FOUND THE BUG!!! IS THE LUA FUNCTION “CLOSE”, ITS ALWAYS ACTIVE AND CLOSES AGAIN AND AGAIN THE GAME!!

# NOW, WITH THIS INFORMATION, REVERT THE REVERTS THAT YOU HAVE DONE, AND I WILL FIX THE BUG!!

**Comment by Theoyeah** [comment]
Fixed
