### ISSUE TITLE
judgement counter not showing shits 

### ISSUE THREAD

**Issue by Theoyeah** [Theoyeah/Theoyeah-Engine#204]
### Describe your bug here.

![image](https://user-images.githubusercontent.com/97792861/175935095-79b93baa-d844-481a-9240-47635a107d96.png)

### Are you modding a build from source or with Lua?

F*ck is from the engine

### What is your build target?

FROM THE ENGINE!!!!

### Did you edit anything in this build? If so, mention or summarize your changes.

Not even

**Comment by Wither362** [comment]
well, i dont find any bug, error, and things like that

**Comment by Wither362** [comment]
btw im updating the engine

**Comment by Wither362** [comment]
btw, should i add a keybind for autosaving when you are charting?
