### ISSUE TITLE
oh god

### ISSUE THREAD

**Issue by Theoyeah** [Theoyeah/Theoyeah-Engine#207]
### Describe your bug here.

idk who did that but the numscore and combo is only showing after the 10 combo

### Are you modding a build from source or with Lua?

F*ck is from the engine

### What is your build target?

FROM THE ENGINE!!!!

### Did you edit anything in this build? If so, mention or summarize your changes.

f

**Comment by Wither362** [comment]
Yeah, it’s from the combo thing, I will repair it

**Comment by Wither362** [comment]
Fixed
