### ISSUE TITLE
quick thing for source coders that can help A LOT

### ISSUE THREAD

**Issue by TonyTimee** [Theoyeah/Theoyeah-Engine#219]
### What feature do you want to get added on the **base** engine?

replace

```trace('oh no its returning null NOOOO');```

with

```trace('oh no ' + key + ' is returning null NOOOOO');```

basiclly in Paths.hx, it will tell you the exact source where it is returning null,

example
```oh no pixelUI/notes/circle is returning null NOOOOOOO```
will prompt in the command bar and not ```oh no its returning null NOOOO```

**Comment by Wither362** [comment]
Didnt i did this before?

**Comment by TonyTimee** [comment]
> Didnt i did this before?

Think so

**Comment by Wither362** [comment]
What i did is: `trace('oh no ' + key + ' in ' + - where + ' is returning null NOOOOO');`
