### ISSUE TITLE
Add vs dave and bambi mechanics

### ISSUE THREAD

**Issue by PHGaming121** [Theoyeah/Theoyeah-Engine#232]
### What feature do you want to get added on the **base** engine?

What do you think about adding some mechanics from vs dave and bambi mods?

Like this:
Eyesores
Something happens when we press 7(like crash game,or load another song)
Window move mechanic
Window pop-up event
Disable ghost tapping on songs
Wavy effect on Background

Plz add this

**Comment by PHGaming121** [comment]
https://github.com/Joalor64GH/Strident-Engine
I found the code from here

**Comment by Wither362** [comment]
In lua, or like events?

**Comment by PHGaming121** [comment]
Como eventos em source code

**Comment by PHGaming121** [comment]
In events in source code

**Comment by PHGaming121** [comment]
if you want, plz add option for different note skin for opponent and boyfriend (like vs dave and bambi notes)

**Comment by Wither362** [comment]
> In events in source code

Ok, I will do it when I get back to Madrid, in 15 days aprox.. ok?

**Comment by Wither362** [comment]
> ### What feature do you want to get added on the **base** engine?
> What do you think about adding some mechanics from vs dave and bambi mods?
> 
> Like this: Eyesores Something happens when we press 7(like crash game,or load another song) Window move mechanic Window pop-up event Disable ghost tapping on songs Wavy effect on Background
> 
> Plz add this

Ok ok, can you edit (or create another one) this issue to be like this:

```
### Adding Dave and Bambi events
List of events:
- [ ] Eyesores
- [ ] Press 7 do something
- [ ] Window move mechanic
- [ ] Window pop-up event
- [x] Disable ghost tapping on songs (this is already added with the _SetProperty_ event)
- [ ] Wavy effect on Background
```
(Copy and paste that code into the new/this issue

**Comment by PHGaming121** [comment]
Ok i will close this and open another one
