### ISSUE TITLE
Add the "mods" tab/option like in the official engine

### ISSUE THREAD

**Issue by dragao2elastico** [Theoyeah/Theoyeah-Engine#243]
### What feature do you want to get added on the **base** engine?

Add the "mods" tab/option like in the official engine.
For a better management of mods in the mods folder I think you should add the mod tab in the engine!
![imagem_2022-09-25_124542546](https://user-images.githubusercontent.com/85897840/192152403-39731f19-11a0-40e2-ad0c-8151fc609cf9.png)

**Comment by Wither362** [comment]
You already can do that!
Go to the main menu and click 7, there is an option called "Mod Manager", it's the same!

Note: if it doesn't have any mods, try going back and selecting it again

**Comment by Wither362** [comment]
But I can convince theoyeah to add it to main menu if you want

**Comment by dragao2elastico** [comment]
So I just ask you to put a warning on readme.md about this!

**Comment by Wither362** [comment]
> So I just ask you to put a warning on readme.md about this!

Ok, thanks about that!

Fixed in https://github.com/Theoyeah/Theoyeah-Engine/commit/c856aef2a164ad02a71b35043aaae894040ec7f5
