### ISSUE TITLE
Add Shaders

### ISSUE THREAD

**Issue by PHGaming121** [Theoyeah/Theoyeah-Engine#263]
### What feature do you want to get added on the **base** engine?

I think its a good idea add the shaders from os engine to this engine

https://github.com/notweuz/FNF-OSEngine
Link for OS engine

The code to add the shader will be the same:

Example
For Chromatic Abberation we type:
addChromaticAbberationEffect(camHUD, 0.017);

camHUD is the camera of the shader, and 0.017 is the amplitude of the shader

PLZ ADD IT

**Comment by Wither362** [comment]
bro, its already in, but ill do it easier for you...

https://github.com/Theoyeah/Theoyeah-Engine/commit/aa9dd2251d4f08548eb7a4fdaaf428ffff25cec5
