### ISSUE TITLE
HTML5

### ISSUE THREAD

**Issue by LEVIXDDLMAO** [Theoyeah/Theoyeah-Engine#265]
### What is your question?

Can I help with html5?

### What type of question is? Of LUA, or source?

Source

**Comment by Wither362** [comment]
Yes, if you want

**Comment by Theoyeah** [comment]
uuhhhh yes it depends on what will you do ?

**Comment by Wither362** [comment]
> 

They are cool, I’ve seen them working, and they can fix compiling problems too

**Comment by LEVIXDDLMAO** [comment]
so do i?

**Comment by Wither362** [comment]
> so do i?

Yeah, if you like…

**Comment by LEVIXDDLMAO** [comment]
im down to help-
