### ISSUE TITLE
help needed: cannot install 4.0 version of engine

### ISSUE THREAD

**Issue by fnfporterhi** [Theoyeah/Theoyeah-Engine#266]
### Describe your problem here.

i downloaded the installer on my PC, it installed 3.0, not 4.0. is this supposed to happen?

ignore the modding stuff, i selected random shit except for windows x32

### Are you modding a build from source or with Lua?

I added a new system

### What is your build target?

Windows x32

### Did you edit anything in this build? If so, mention or summarize your changes.

nope i used the installer like normal

### Can you show the code? Only in case that you want

```lua
hx
udkdodnsisdnduenejsjsd

lua:

haxe:

other:
```

**Comment by Theoyeah** [comment]
Weird, the engine does says that it is 4.0 beta 2. Are you installing 4.0, or 4.0 beta 2 ?
Tho, take note that a prompt says that you're engine is outdated, it is because it is a beta, so it isn't considered as the newest version.

**Comment by fnfporterhi** [comment]
the engine is saying it’s running on 3.0, and it said it installed 4.0 beta 2

**Comment by Theoyeah** [comment]
it is normal, it was a detail that i forgot to change
You can still play it normally and you have the things of 4.0 beta 2

**Comment by fnfporterhi** [comment]
oh ok! thanks!

**Comment by fnfporterhi** [comment]
you’re the best helper! thanks so much!

**Comment by Theoyeah** [comment]
> you’re the best helper! thanks so much!

Nan, it was just a dumb error of my part. Hope you will have fun with it
