### ISSUE TITLE
Can't compile :/

### ISSUE THREAD

**Issue by OurfGames** [Theoyeah/Theoyeah-Engine#269]
### Describe your problem here.

PS C:\Users\CCE\Desktop\Theoyeah-Engine-main\Theoyeah-Engine-main> lime test windows
source/PlayState.hx:79: characters 8-22 : Type not found : vlc.MP4Handler
source/PlayState.hx:1817: characters 13-23 : Type not found : MP4Handler
PS C:\Users\CCE\Desktop\Theoyeah-Engine-main\Theoyeah-Engine-main>

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

No

### Can you show the code? Only in case that you want

```lua
hx
udkdodnsisdnduenejsjsd

PS C:\Users\CCE\Desktop\Theoyeah-Engine-main\Theoyeah-Engine-main> lime test windows
source/PlayState.hx:79: characters 8-22 : Type not found : vlc.MP4Handler
source/PlayState.hx:1817: characters 13-23 : Type not found : MP4Handler
PS C:\Users\CCE\Desktop\Theoyeah-Engine-main\Theoyeah-Engine-main>
```

**Comment by Wither362** [comment]
Yeah, I have to fix that

**Comment by OurfGames** [comment]
ok i thought i was dumb XD

**Comment by Wither362** [comment]
And there is a lot of bugs right now, so I recommend you to compile the branch `bugfixed` in case that you want the engine working

**Comment by Theoyeah** [comment]
Yeah, please use bugfixed while we try our best fixing the bugs, almost everything is fixed, we need to fix some stages and we will merge when we are sure it is fixed
